version: '3.8'

services:
  backend:
    build: ./Capstone_Project_Backend
    ports:
      - "21103:5001"
    env_file:
      - ./Capstone_Project_Backend/.env
    networks:
      - app-network

  frontend:
    build: ./Capstone_Project_Frontend
    ports:
      - "225:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
